### ISSUE TITLE
An error running CI deployment

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/map-config-api#28]
https://github.com/Greenstand/map-config-api/actions/runs/3450268880/jobs/5758758690

**Comment by dadiorchen** [comment]
@Kpoke can you take a look this?

**Comment by Kpoke** [comment]
I think this is the issue, semantic release is not picking the commit as an update, so it is thinking there is no new change to deploy
![image](https://user-images.githubusercontent.com/28721558/201821191-346a798c-8afc-4c98-b9d8-8c2db89c3684.png)

**Comment by dadiorchen** [comment]
@RubenSmn maybe you can commit some fake commit with "fix: ci"

**Comment by RubenSmn** [comment]
I did it, it worked. When commiting I got this message about the commit conventions

```
Checking commit message for compliance with conventional commits
Speficiation: https://www.conventionalcommits.org/en/v1.0.0/
```

So how did this commit message pass that? [ref_id will not type-cast strings into numbers](https://github.com/Greenstand/map-config-api/commit/8b5e4dbcccc47583169ea318b5ffa30c45dad62c)

**Comment by Kpoke** [comment]
Hmm... Not sure why, there should be a pre-commit hook that handles  that check and forces the convention
